# Generated by Django 5.1.4 on 2025-02-17 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supporteddevice',
            name='type',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
