# Generated by Django 5.1.4 on 2025-02-08 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supporteddevice',
            name='address',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
