# Generated by Django 5.1.4 on 2025-01-18 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_devicelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceLogDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_energy_usage', models.FloatField(default=0.0)),
                ('status_usage_details', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceLogMonthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('total_energy_usage', models.FloatField(default=0.0)),
                ('daily_summaries', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RoomLog5Sec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy_usage', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomLogDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_energy_usage', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='RoomLogMonthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('total_energy_usage', models.FloatField(default=0.0)),
            ],
        ),
        migrations.RenameModel(
            old_name='DeviceLog',
            new_name='DeviceLog5Sec',
        ),
        migrations.RemoveConstraint(
            model_name='device',
            name='unique_device_per_home',
        ),
        migrations.RemoveField(
            model_name='device',
            name='smart_home',
        ),
        migrations.AddField(
            model_name='devicelogdaily',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.device'),
        ),
        migrations.AddField(
            model_name='devicelogmonthly',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.device'),
        ),
        migrations.AddField(
            model_name='room',
            name='smart_home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='api.smarthome'),
        ),
        migrations.AddField(
            model_name='device',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='api.room'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(fields=('name', 'room'), name='unique_device_in_room'),
        ),
        migrations.AddField(
            model_name='roomlog5sec',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.room'),
        ),
        migrations.AddField(
            model_name='roomlogdaily',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.room'),
        ),
        migrations.AddField(
            model_name='roomlogmonthly',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.room'),
        ),
    ]
