# Generated by Django 5.1.4 on 2025-03-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_supporteddevice_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='supporteddevice',
            name='consumption_rate',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
