# Generated by Django 5.1.4 on 2025-03-02 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_supporteddevice_consumption_rate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeviceLog5Sec',
            new_name='DeviceLog1Min',
        ),
        migrations.RenameModel(
            old_name='RoomLog5Sec',
            new_name='RoomLog1Min',
        ),
    ]
