# Generated by Django 5.1.4 on 2025-01-26 04:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_roomlog5sec_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicelog5sec',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
