# Generated by Django 5.1.4 on 2025-03-07 01:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_devicelog5sec_devicelog1min_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyGeneration1Min',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy_generation', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.smarthome')),
            ],
        ),
        migrations.CreateModel(
            name='EnergyGenerationDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_energy_generation', models.FloatField(default=0.0)),
                ('daily_generation_details', models.JSONField(default=dict)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.smarthome')),
            ],
        ),
        migrations.CreateModel(
            name='EnergyGenerationMonthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('total_energy_generation', models.FloatField(default=0.0)),
                ('daily_summaries', models.JSONField(default=dict)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.smarthome')),
            ],
        ),
    ]
