# Generated by Django 5.1.4 on 2025-03-07 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_energygeneration1min_energygenerationdaily_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energygenerationdaily',
            name='daily_generation_details',
        ),
        migrations.RemoveField(
            model_name='energygenerationmonthly',
            name='daily_summaries',
        ),
    ]
