# Generated by Django 5.1.4 on 2025-03-14 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_energygenerationdaily_daily_generation_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supporteddevice',
            name='number',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
