# Generated by Django 5.1.4 on 2025-03-14 22:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_homeioroom_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='analogue_value',
            field=models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(1, message='Value must be at least 1'), django.core.validators.MaxValueValidator(10, message='Value cannot be greater than 10')]),
        ),
    ]
