# Generated by Django 5.1.4 on 2025-03-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='smarthome',
            name='join_password',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
